### ISSUE TITLE
.env file

### ISSUE THREAD

**Issue by joeblack2k** [louisgrasset/touitomamout#101]
as demo i'am trying to copy @marionawfal on twitter to bluesky marionawfal.bsky.scoial
the docker isnt crashing but nothing is happening either.. is this set up correctly?

```
// Data source
TWITTER_HANDLE=marionawfal

// API

BLUESKY_INSTANCE=marionawfal
BLUESKY_IDENTIFIER=marionawfal.bsky.scoial
BLUESKY_PASSWORD=PASSWORD

// Touitomamout
INSTANCE_ID=1
EXECUTION=manual
# EXECUTION=pm2
SYNC_MASTODON=false
SYNC_BLUESKY=true
SYNC_PROFILE_DESCRIPTION=true
SYNC_PROFILE_PICTURE=true
SYNC_PROFILE_HEADER=true
SYNC_PROFILE_NAME=true

```

**Comment by kai17** [comment]
I think you need to have 
BLUESKY_INSTANCE="bsky.social"
and use App password for BlueSky. Having said that, my setup is very similar, but all I get is 
content-mapper  ✔ tweets: total: 0 retweets: 0 replies: 0 quotes: 0
So my  tweets are completely ignored.

**Comment by joeblack2k** [comment]
Thanks, i fixed that but it still doesnt work,

getting allot of this:
<img width="1251" alt="Screenshot 2023-10-28 at 22 02 37" src="https://github.com/louisgrasset/touitomamout/assets/3456102/0e798201-67b5-48ed-bf8d-dfed2f2746fe">

**Comment by louisgrasset** [comment]
Hey, I would first recommend you to use a Twitter account to be authenticated, the more I test Touitomamout, the more I see Twitter limiting the data accessible without being logged int.

Also, you can generate your `.env` file here:
https://louisgrasset.github.io/touitomamout/docs/tools/env-generator.

**Comment by joeblack2k** [comment]
i have created a twitter account and used the .env creator (awesome!) 

but still thousands of logs (190mb log file) with the same text

<img width="1507" alt="Screenshot 2023-10-29 at 14 15 36" src="https://github.com/louisgrasset/touitomamout/assets/3456102/6d7f024b-b704-4c7d-9cb6-a0ff6a62896b">


this is the new .env:

`TWITTER_HANDLE=marionawfal
TWITTER_USERNAME=mirrorxwittter
TWITTER_PASSWORD=PASSWORD
BLUESKY_INSTANCE=bsky.social
BLUESKY_IDENTIFIER=marionawfal.bsky.social
BLUESKY_PASSWORD=PASSWORD
SYNC_PROFILE_DESCRIPTION=false
SYNC_PROFILE_PICTURE=false
SYNC_PROFILE_HEADER=false
SYNC_PROFILE_NAME=false
INSTANCE_ID=1`

**Comment by joeblack2k** [comment]
it has something todo with the docker container , because when i enter it into the docker with portainer it works:

<img width="686" alt="Screenshot 2023-10-29 at 17 53 14" src="https://github.com/louisgrasset/touitomamout/assets/3456102/0b1eca7b-529b-4621-b9e2-87a7ea31bee6">

**Comment by joeblack2k** [comment]
well it starts..
```


🦤 client       ✔ connected (using credentials)
☁️ client       ✖ authentication failure
TypeError: fetch failed
profile-sync    ⠧ parsingError: Failed to perform request.
    at requestApi (/app/node_modules/@the-convocation/twitter-scraper/dist/api.js:32:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getProfile (/app/node_modules/@the-convocation/twitter-scraper/dist/profile.js:63:17)
    at async Scraper.getProfile (/app/node_modules/@the-convocation/twitter-scraper/dist/scraper.js:43:21)
    at async profileSynchronizerService (file:///app/dist/services/profile-synchronizer.service.js:17:21)
    at async touitomamout (file:///app/dist/index.js:18:5)
    at async file:///app/dist/index.js:31:1
bot@toetie:/app$ 
```
