### ISSUE TITLE
XRPCError: Invalid app.bsky.feed.post record: Record/text must not be longer than 300 graphemes

### ISSUE THREAD

**Issue by kai17** [louisgrasset/touitomamout#115]
With the latest version (commit cceb9d), touitomamout pulls the tweets from https://twitter.com/kai_arzheimer and reposts them at https://bsky.app/profile/kaiarzheimer.bsky.social. However, it chokes on this tweet https://twitter.com/kai_arzheimer/status/1716520276488249713 with an error about using more than 300 graphemes (the tweet is definitively shorter). The script than hangs for a few seconds before terminating. My more recent tweets do not get synchronised. Instead, my older tweets get duplicated on Bluesky.

**Comment by louisgrasset** [comment]
I'll look into that. I added some checks in the codebase, they are already passing... 🤔

**Comment by louisgrasset** [comment]
A fixed has been merge regarding the duplication. It was related to a cache migration failure.
If you want to start the sync from a specific tweet, you can add the following in your cache file:

```
{
...
posts: {
    ...
    "yourTweetIdHere": {
       mastodon: ["correspondingMastodonId"]
    }
    ...
}
...
}

```

**Comment by kai17** [comment]
Thank you again. I just pulled from github and ran the script again, but the result is the same (see the attached screenshot). The first part of the tweet (w/ot the link) is posted again on Bluesky (now for the 9th time), then the script hangs for a few seconds and terminates.
Should I try deleting the cache and/or reinstall from scratch?
![screenshot](https://github.com/louisgrasset/touitomamout/assets/2708200/d2f4eb0e-63a0-4b71-8b40-e4029cd5d47b)

**Comment by louisgrasset** [comment]
Sounds like the AtProto relies on Graphemer to count text length, not on a simple `string.length`.

From what I see, two things seems important here:
- your tweet is leveraging emojis (which are not simple string characters)
- atProto checks the text length using the following code:
```
// counts the number of graphemes (user-displayed characters) in a string
export const graphemeLen = (str: string): number => {
  const splitter = new Graphemer()
  return splitter.countGraphemes(str)
}
```

Thanks to your issue & details, I'll try to reproduce & find a fix
