### ISSUE TITLE
feat: support bluesky domain-based handle

### ISSUE THREAD

**Issue by maxzhelezov** [louisgrasset/touitomamout#121]
Is there a way to connect bluesky account that sits on domain handle i.e. @test.com?

I've set BLUESKY_IDENTIFIER to domain handle but it doesn't seem to work
Tried leaving BLUESKY_INSTANCE free, with bsky.social or with domain and it also not working

Touitomamout detects twitter posts but writes that 0 posts synced so far and doesn't throw any errors regarding bluesky auth

**Comment by louisgrasset** [comment]
Hey @maxzhelezov, this is one of the last "obvious" use case I still have to cover.
It may be super quick, but I prefer checking that on my side in the next days.

I'll make sure to update this Issue if needed 🎉

**Comment by louisgrasset** [comment]
Hey, I've been able to post to a domain based handle.
What was the touitomamout version you were running?
