### ISSUE TITLE
feat: provide link metadata to bluesky post if any 

### ISSUE THREAD

**Issue by kai17** [louisgrasset/touitomamout#122]
Many sites define social media "cards" using tags like 
```html
<meta name="twitter:card" content="summary"></meta>
``` 
When I post a link to such a site on twitter, an image/summary are attached. This attachment does not carry over to Bluesky. 

Compare these posts

https://twitter.com/kai_arzheimer/status/1722587507693351295
https://bsky.app/profile/kaiarzheimer.bsky.social/post/3kdqxizx5ra2m

I suspect this is because Bluesky (at least on the web) requires an extra click to confirm that one wants to attach the card. It would be great if this confirmation could be given via the API by the script.

**Comment by louisgrasset** [comment]
Good catch! I'll have a look

**Comment by mcleinn** [comment]
I needed the same feature and I added a quick fix in a fork, together with video previews: https://github.com/louisgrasset/touitomamout/compare/main...mcleinn:touitomamout-bskyvid:main

But this is only a quick and dirty solution, if you have time then better wait until @louisgrasset adds the feature to the main repo

**Comment by kai17** [comment]
Thank you, that's great! Not a programmer, so all I can contribute to this
wonderful program is bug reports and ideas for new features ;-)
--
Professor of Politics
Department of Political Science / University of Mainz
http://www.kai-arzheimer.com / http://twitter.com/kai_arzheimer

**Comment by mcleinn** [comment]
Great. Please note that I ran into issues if the indicated preview picture (og:image) is bigger than 975 kB or so.
That especially happens when the og:image is a png. It will fail to upload to Bluesky with an error. 
So either you need to ignore the image, chose another one (risky) or scale it down (I am using "sharp" module for that)

**Comment by louisgrasset** [comment]
Compression work is started, but I'll not merge it with card management.
