### ISSUE TITLE
Bluesky: Twitter previews not turned into Bluesky preview cards

### ISSUE THREAD

**Issue by mcleinn** [louisgrasset/touitomamout#123]
Twitter posts with link previews - that is, almost all tweets with links - are not converted into Bluesky preview cards (type **app.bsky.embed.external**), but instead into two Bluesky posts: first with text, second one quoting the first, with the link. 

IMHO that is less readable and unnecessary, as a similar function exists.
The previews will be more similar to old style Twitter previews, with headlines and descriptions. 
There is documentation on the ATProto protocol page on how to create previews based on OG tags:
https://atproto.com/blog/create-post (example at the bottom)

<img width="442" alt="screen" src="https://github.com/louisgrasset/touitomamout/assets/3145561/aacfaaa0-503b-454b-bb82-0ad7aa97b257">

**Comment by mcleinn** [comment]
This is demo code converted to TS by ChatGPT using the node-fetch library to make HTTP requests and node-html-parser to parse HTML and extract information:

`import fetch from 'node-fetch';
import { parse } from 'node-html-parser';

interface EmbedCard {
  uri: string;
  title: string;
  description: string;
  thumb?: string;
}

async function fetchEmbedUrlCard(accessToken: string, url: string): Promise<EmbedCard> {
  // the required fields for every embed card
  let card: EmbedCard = {
    uri: url,
    title: "",
    description: "",
  };

  // fetch the HTML
  const resp = await fetch(url);
  if (!resp.ok) throw new Error(`HTTP error! status: ${resp.status}`);
  const html = await resp.text();
  const root = parse(html);

  // parse out the "og:title" and "og:description" HTML meta tags
  const titleTag = root.querySelector('meta[property="og:title"]');
  if (titleTag) {
    card.title = titleTag.getAttribute('content');
  }
  const descriptionTag = root.querySelector('meta[property="og:description"]');
  if (descriptionTag) {
    card.description = descriptionTag.getAttribute('content');
  }

  // if there is an "og:image" HTML meta tag, fetch and upload that image
  const imageTag = root.querySelector('meta[property="og:image"]');
  if (imageTag) {
    let imgURL = imageTag.getAttribute('content');
    // naively turn a "relative" URL (just a path) into a full URL, if needed
    if (imgURL && !imgURL.includes('://')) {
      imgURL = new URL(imgURL, url).href;
    }
    const imgResp = await fetch(imgURL);
    if (!imgResp.ok) throw new Error(`HTTP error! status: ${imgResp.status}`);

    const IMAGE_MIMETYPE = 'image/jpeg'; // replace with the actual image MIME type if needed
    const blobResp = await fetch('https://bsky.social/xrpc/com.atproto.repo.uploadBlob', {
      method: 'POST',
      headers: {
        'Content-Type': IMAGE_MIMETYPE,
        'Authorization': `Bearer ${accessToken}`,
      },
      body: await imgResp.buffer(),
    });
    if (!blobResp.ok) throw new Error(`HTTP error! status: ${blobResp.status}`);
    const blobData = await blobResp.json();
    card.thumb = blobData.blob;
  }

  return card;
}
`

**Comment by louisgrasset** [comment]
**Images**
The fact links are not posted with an image is right. This issue has already been reported yesterday (https://github.com/louisgrasset/touitomamout/issues/122)

**Formatting**
Since the tweet text + the link are longer than the 300 chars Bluesky limit, a content split is mandatory.

Content (232 chars or something like this) then a link (about 100 chars here).

Don't forget that links `t.co` are converted before being posted.

**Comment by mcleinn** [comment]
Maybe it would be possible to put links through another URL shortener to avoid the posted message being longer than the original message?

**Comment by louisgrasset** [comment]
It might be interesting to. The point here is to post on platforms that are by definition more open. 

Relying on a shortener may not be the best idea even though it would let you get a single tweet in this case.

I'll look into that, but I don't want to enforce a specific tool.

**Comment by mcleinn** [comment]
I added both features I needed to my fork:
https://github.com/louisgrasset/touitomamout/compare/main...mcleinn:touitomamout-bskyvid:main

In Bluesky, it supports both previews with links to videos & previews to links (links are then removed from chunks, empty chunks deleted) - this is just a quick workaround for myself, but you might have a look

<img width="442" alt="screen" src="https://github.com/louisgrasset/touitomamout/assets/3145561/e53d5c9e-f28b-4258-96f0-fc6470c2387e">
<img width="432" alt="video" src="https://github.com/louisgrasset/touitomamout/assets/3145561/4c3f024a-8ce5-4189-8fb2-a5fefdf96fb2">

Thank you again for the good work!
