### ISSUE TITLE
.env not accessible in docker environnement

### ISSUE THREAD

**Issue by JoshuaHolme** [louisgrasset/touitomamout#125]
Trying to run in an unraid docker container. I added all the variables in the config and when I try to run it I get the following error.
```

(node:8) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
Error: No suitable .env file found.
    at file:///app/dist/constants.js:13:11
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

```

**Comment by louisgrasset** [comment]
These issues are often related to wrong file permissions

**Comment by louisgrasset** [comment]
Second issue mentioning file access problems: #130.

**Comment by JoshuaHolme** [comment]
I am entering the environment variables in the GUI in unpaid, not in an .env file, so I don't know how there could be file permission issues

**Comment by louisgrasset** [comment]
Oh, I see. So Touitomamout will only look for a file, that will be loaded into the script. So if there is no file, it will stops

**Comment by omahon** [comment]
Getting this error when using the environment variables in a .env file, all file permissions seem to be allowed so not sure what is causing the block, would appreciate any insight you can provide on this!
