### ISSUE TITLE
Unable to download media: fetch failed  (after twitter login)

### ISSUE THREAD

**Issue by beatstick** [louisgrasset/touitomamout#130]
**Describe the bug**
I tested the docker as well as the manual sync.
Both give the error:

 🦤 client       ✔ connected (using credentials)
touitomamout  | Error updating cookies file: [Error: EACCES: permission denied, open '/data/cookies.xxx.json'] {
touitomamout  |   errno: -13,
touitomamout  |   code: 'EACCES',
touitomamout  |   syscall: 'open',
touitomamout  |   path: '/data/cookies.xxx.json'
touitomamout  | }
touitomamout  | Error: Unable to download media:
touitomamout  | TypeError: fetch failed
touitomamout  |     at mediaDownloaderService (file:///app/dist/services/media-downloader.service.js:9:15)
touitomamout  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
touitomamout  |     at async profileSynchronizerService (file:///app/dist/services/profile-synchronizer.service.js:23:11)
touitomamout  |     at async touitomamout (file:///app/dist/index.js:19:5)
touitomamout  |     at async file:///app/dist/index.js:33:1

**To Reproduce**
use .env-file:

TWITTER_HANDLE=xxx
TWITTER_USERNAME=xxx
TWITTER_PASSWORD=mysecretpw
MASTODON_INSTANCE=layer8.space
MASTODON_ACCESS_TOKEN=mastodon_generated_token
DAEMON=false
SYNC_FREQUENCY_MIN=30
SYNC_PROFILE_DESCRIPTION=true
SYNC_PROFILE_PICTURE=true
SYNC_PROFILE_HEADER=true
SYNC_PROFILE_NAME=true

sart sync: 
node ./dist/index.js .env

**Expected behavior**
syncing between twitter and mastodon is happening.

**Comment by beatstick** [comment]
Partly solved: Twitter login failed because of addblocklist running in the background.
Now the client cannot create cokie- and cache-files, and also the tweets do not appear on mastodon. What could be the problem now?

 🦤 client       ✔ connected (using credentials)
touitomamout  | Error updating cookies file: [Error: EACCES: permission denied, open '/data/cookies.xxx.json'] {
touitomamout  |   errno: -13,
touitomamout  |   code: 'EACCES',
touitomamout  |   syscall: 'open',
touitomamout  |   path: '/data/cookies.xxx.json'
touitomamout  | }
touitomamout  | 
touitomamout  | [touitomamout] Error while updating the cache file
touitomamout  |                └─ 🦣. Error: EACCES: permission denied, open '/data/cache.xxx.json'
touitomamout  |     at Object.open (node:internal/fs/sync:78:18)
touitomamout  |     at Object.openSync (node:fs:565:17)
touitomamout  |     at writeFileSync (node:fs:2288:35)
touitomamout  |     at writeToCacheFile (file:///app/dist/helpers/cache/write-to-cache-file.js:6:9)
touitomamout  |     at updateCacheEntry (file:///app/dist/helpers/cache/update-cache-entry.js:12:9)
touitomamout  |     at async profileSynchronizerService (file:///app/dist/services/profile-synchronizer.service.js:126:5)
touitomamout  |     at async touitomamout (file:///app/dist/index.js:19:5)
touitomamout  |     at async file:///app/dist/index.js:33:1 {
touitomamout  |   errno: -13,
touitomamout  |   code: 'EACCES',
touitomamout  |   syscall: 'open',
touitomamout  |   path: '/data/cache.xxx.json'
touitomamout  | }
touitomamout  | profile-sync    ✔ task finished
touitomamout  | content-mapper  ✔ tweets: total: 2 retweets: 0 replies: 0 quotes: 0
touitomamout  | content-mapper  ✔ task finished
touitomamout  | content-sync    ℹ post: → generated « Greetings fellow members,... » → 
touitomamout  | content-sync    ℹ post: → generated « test... »                      → 
touitomamout  | 
touitomamout  | 🦤 → 🦣+☁️
touitomamout  | Touitomamout sync | v1.4.0
touitomamout  | | Twitter handle: @xxx
touitomamout  | | 00002  ʲᵘˢᵗ ˢʸⁿᶜᵉᵈ ᵖᵒˢᵗˢ
touitomamout  | | 00000  ˢʸⁿᶜᵉᵈ ᵖᵒˢᵗˢ ˢᵒ ᶠᵃʳ
touitomamout  | Run daemon every 3min

**Comment by louisgrasset** [comment]
` touitomamout | Error updating cookies file: [Error: EACCES: permission denied, open '/data/cookies.xxx.json'] {`

There is an high chance the bind volume in docker doesn't have the right permissions

**Comment by beatstick** [comment]
I've managed to get it to run with the manual method for now. There are no errors when the script is running, however nothing gets updated on mastodon. 

This is the app running on Mastodon:
[Touitomamout](https://layer8.space/settings/applications/xxx) 	read:accounts write:accounts write:media write:statuses

I changed the settings according to the wiki, and set sync to every 3 minutes for now, but I still don't get any crossposts nor changes to the profile pic  or anything synced really.

**Comment by louisgrasset** [comment]
Can you write down your configuration?

**Comment by beatstick** [comment]
Ah I found the error, I need to set the parameter SYNC_MASTODON=true
in the .env file. 

It's in the documentation, but missing from the environment file generator currently. Maybe it should be added so users don't miss it? 

About the docker error. I've got no clue why the permissions don't work. Other containers I am running do not seem to have that problem.

**Comment by louisgrasset** [comment]
Wow, good catch, I totally missed it!

**Comment by louisgrasset** [comment]
🐛  Fixed!
https://github.com/louisgrasset/touitomamout/pull/141/

**Comment by louisgrasset** [comment]
Docker related issue: https://github.com/louisgrasset/touitomamout/issues/125

I'll focus on a single Issue.
