### ISSUE TITLE
Unable to build in PM2

### ISSUE THREAD

**Issue by flatlinee** [louisgrasset/touitomamout#155]
**Describe the bug**
Can't build with PM2. Gives me this error:

C:\Users\Neil\.pm2\home\Neil\services\touitomamout>npm run pm2

> touitomamout@1.6.3 pm2
> bash deployment/pm2.sh

deployment/pm2.sh: line 2: $'\r': command not found
deployment/pm2.sh: line 5: $'\r': command not found
deployment/pm2.sh: line 7: $'\r': command not found
deployment/pm2.sh: line 9: syntax error near unexpected token `$'do\r''
'eployment/pm2.sh: line 9: `for env in .env*; do

**To Reproduce**
Run npm run pm2

I had to install some linux distribution to even make the bash script work, which wasn't mentioned in the tutorial at all, and I also have no idea how to "inject the .env file" as mentioned in the tutorial as well. It's really not written for beginners and just doesn't include commands sometimes.

**Comment by louisgrasset** [comment]
You are running in a issue related to the fact you are trying to run the project under a Windows environment.

The ` line 2: $'\r': command not found` error comes from the fact windows do not handle files the same way linux/macos do.
I suggest you to jump into one of the first StackOverflow answers to fix this.

Regarding the fact you had to install the WSL (Windows Subsystem for Linux), well, to be honest I did not tested the deployment on a windows machine, sorry for that.

Let me know how's your debugging session goes with the CRLF/LF issue, I'll be happy to fix any issue in the code 🌟
