### ISSUE TITLE
feat: Support (Meta) Threads

### ISSUE THREAD

**Issue by quassy** [louisgrasset/touitomamout#157]
It would be nice to also be able to post to [Threads](https://www.threads.net/) as it's one of the current more-or-less popular microblogging services right now. There seem to be [projects](https://github.com/threadsjs/threads.js) to provide / use the Threads API which could be useful, but I don't know how mature they are.

**Comment by louisgrasset** [comment]
Hello, I'm waiting for Meta to properly publish the API
