### ISSUE TITLE
Troubleshoot Lack of Tweet Threads

### ISSUE THREAD

**Issue by QuinnyPig** [louisgrasset/touitomamout#169]
I've created a few small threads / self replies on Twitter; unfortunately only the first tweet shows up. Is there a decent way to boost log verbosity to figure out what's going on? This may be a limitation of how Twitter's broken lately.

Yes, I have a secondary account that Touitomamout is using to log in to scrape the source account's tweets.

**Comment by louisgrasset** [comment]
The `DEBUG` set to true could help you. 

But I think logs could be improved. But I don't have any bandwidth in the following weeks...

**Comment by louisgrasset** [comment]
Btw, can you provide a link to the thread you were trying to sync?

**Comment by QuinnyPig** [comment]
Ran a couple of experiments today.

[This one](https://x.com/QuinnyPig/status/1754618480060739940?s=20) replicated the initial tweet, but the [followup](https://x.com/QuinnyPig/status/1754705430629278090?s=20) (hours later) didn't repeat. 

I posted[ this two tweet thread](https://x.com/QuinnyPig/status/1754530090132943168?s=20) one right after the other between Touitomout runs; curiously neither one synced anywhere. 

As a data point, I've never had a tweet thread / self reply successfully sync from that account.

**Comment by louisgrasset** [comment]
We might be facing some tweet retrieval issue, I just tested it, and nothing gets pulled from Twitter...

**Comment by QuinnyPig** [comment]
Makes sense; the platform has massively degraded. It's inconsistent; some stuff is still syncing.
