### ISSUE TITLE
Recent Tweets aren't being pulled in.

### ISSUE THREAD

**Issue by bawanyadam** [louisgrasset/touitomamout#172]
**Describe the bug**
Touitomamout setup via cron method/cli with .env file is configured correctly is pulling day old data, when Twitter account has posted on the present day.

**To Reproduce**
1. Visit https://twitter.com/wsdot_traffic
2. Visit https://bsky.app/profile/wsdottraffic.bsky.social
3. See discrepancy

**Expected behavior**
The Bluesky account is a day behind while the X account posts multiple times an hour.

Triggering the sync manually runs the script with no errors, but doesn't see anything new to sync.
```
cd /home/bsky-wsdot/services/touitomamout && node ./dist/index.js .env.wsdottraffic
``` 

**Screenshots**
<img width="779" alt="Screenshot 2024-02-13 at 2 36 57 PM" src="https://github.com/louisgrasset/touitomamout/assets/26401930/9d39f93c-c3e3-4fed-899c-1b49a74856da">

**Comment by louisgrasset** [comment]
Yes we're all facing this. I'll try to get a way to address this but I'm fear this will be out of control if Musk has been able to block the scrapper we rely on

**Comment by bawanyadam** [comment]
Gotcha. Figured it might be that but wasn’t sure. Appreciate the work and response!

**Comment by tsueri** [comment]
What was it?
