### ISSUE TITLE
Docker container logging

### ISSUE THREAD

**Issue by hipstersmoothie** [louisgrasset/touitomamout#173]
**Describe the bug**

I'm trying to run in a docker container and its working (I think) but the logs are crazy.

its been running for ~45 seconds

![CleanShot 2024-02-25 at 13 42 02@2x](https://github.com/louisgrasset/touitomamout/assets/1192452/64b0aee2-e4ab-49b2-ba2a-af6b3be29321)

which is taking up my cpu

![CleanShot 2024-02-25 at 13 42 23@2x](https://github.com/louisgrasset/touitomamout/assets/1192452/aa6897b3-70ac-4eb6-ac30-408aef61eb5d)

**To Reproduce**
pretty standard docker config
**Expected behavior**
it doesn't log so much and take up my cpu

**Additional supporting information**
Maybe it's ora outputting to many logs?

**Comment by louisgrasset** [comment]
Could you share here your configuration file? So that we can first try to understand if any human error is located in this issue?
