### ISSUE TITLE
Specific link in tweet blocking the whole sync progress

### ISSUE THREAD

**Issue by IceCodeNew** [louisgrasset/touitomamout#186]
**Describe the bug**

This tweet is blocking the whole sync progress:
https://x.com/niuniu_8964/status/1797545897687122345
```
content-sync    ℹ post: → generated « https://www.gentosha.jp/s... » → ☁️ 1 chunk
Media type not supported (application/json;charset=utf-8)
```

The tweet itself is as simple as a single link, pointing to the following article:
https://www.gentosha.jp/series/joseitachinohinkon

Digging into it, it turns out that the only json resource in the link I shared, was a third-party service loaded by that site. And it should not block the sync progress.

```
https://jsoon.digitiminimi.com/twitter/count.json?callback=jQuery191016546455030799834_1718088660601&url=https%3A%2F%2Fwww.gentosha.jp%2Fseries%2Fjoseitachinohinkon&_=1718088660602
```

**To Reproduce**

1. To manually sync [this tweet](https://x.com/niuniu_8964/status/1797545897687122345)

**Expected behavior**
1. Tweets with links synced without problem
2. Tweets that failed to sync SHOULD NOT BLOCK the whole sync progress

**Screenshots**

<img width="733" alt="image" src="https://github.com/louisgrasset/touitomamout/assets/32576256/8aa358a0-ffba-4dc1-91f7-8705658666d6">

<img width="1224" alt="image" src="https://github.com/louisgrasset/touitomamout/assets/32576256/2ea3a8ab-e4e4-4fc8-b026-593b7365e264">

**Additional supporting information**

version of touitomamout:
```
louisgrasset/touitomamout@sha256:3ba94516e348e1be6a25e8f323cb134c6c12218e7590b3fe7c8fa552ce85cacf
```

**Comment by JoshuaHolme** [comment]
I am also getting the `Media type not supported (application/json;charset=utf-8)` on one of my accounts and it's a huge bummer

**Comment by JoshuaHolme** [comment]
as a workaround if you go into the cache json file, copy the last entry and replace the tweet ID with the id of the tweet that's blocking progress you can get it to skip over it and keep going, until they post another offending tweet that is

**Comment by louisgrasset** [comment]
Hello @ IceCodeNew, the latest `dev` tag of Touitomamout relies on a brand new links redirection management.
I've been able to sync a tweet having this link in it. I'm closing the issue for now.

Obviously, feel free to open another one if the problem persists
