### ISSUE TITLE
Bluesky posts get backdated

### ISSUE THREAD

**Issue by NickBack** [louisgrasset/touitomamout#191]
It's not exactly a "bug" it might be considered a feature, but I'm not sure it's a good one.

When touitomamout crossposts from twitter to bluesky, it backdates the bluesky post to whatever the date of the original tweet was.

I run touitomamout through a local docker, which means it runs once per half an hour at best and might not even run for many hours.

This means that a freshly crossposted twitter to bluesky post might indicate it was posted 2 hours ago, even though it just appeared on bluesky. And I think that's a little weird and probably doesn't really help with engagement.

It is worth noting that Twitter -> Mastodon doesn't work this way. Mastodon time posted is the time which the post actually appeared on the platform, not the time the post was done on twitter.

I would expect Bluesky crossposts to behave the same.

**Comment by louisgrasset** [comment]
Option added: https://github.com/louisgrasset/touitomamout/pull/213
