### ISSUE TITLE
Replies to self are not crossposted as replies to self

### ISSUE THREAD

**Issue by NickBack** [louisgrasset/touitomamout#192]
When creating a chain of posts on twitter, by making an initial post and then replying to it to keep adding more thoughts, it seems the replies are crossposted to mastodon and bluesky as independent posts and not as part of a chain of replies.

Is this something that could be fixed / chained? As it is now, I need to avoid creating threads on twitter if I want crossposting to work without issues.

**Comment by louisgrasset** [comment]
Hello, yes I am aware. I'm working on fixing a lot of issues like that.
Also, I have a twitter client update to release that could address this specific point. I'll have a look
