### ISSUE TITLE
Threads cross posted as posts not chained

### ISSUE THREAD

**Issue by trfetzer** [louisgrasset/touitomamout#194]
**Describe the bug**
I have noticed that a Twitter thread does not properly cross post into a thread. On Bluesky it seems that threads need to be written as comments on the initial tweet. 

See e.g. 

https://bsky.app/profile/trfetzer.com/post/3l2owvg3zgh2x
https://bsky.app/profile/trfetzer.com/post/3l2owvc2b3h2x

versus original thread

https://x.com/fetzert/status/1828364904866181141

This also happens with Mastodon.

**Comment by louisgrasset** [comment]
Related: https://github.com/louisgrasset/touitomamout/issues/192

**Comment by trfetzer** [comment]
I am wondering if a simple solution could be to add a counter as I guess the main issue is detecting what is a thread and what is not without the API. E.g. adapting user behavior. It would be REALLY cool to have this feature.
