### ISSUE TITLE
Support quote tweets using links

### ISSUE THREAD

**Issue by npmanos** [louisgrasset/touitomamout#227]
Would it be possible to add an option to post quote tweets using a link to the quoted post? Or on Bluesky, just using an embeded link preview?

**Comment by louisgrasset** [comment]
Hello, the "technical" point is doable. But it term of vision for this project, I'll decline this idea.

I consider Touitomamout as a tool to synchronize your own original content across multiple platforms.
Any platform-specific content should not be synced & stay on it's own platform
