### ISSUE TITLE
Dynamic timer

### ISSUE THREAD

**Issue by trfetzer** [louisgrasset/touitomamout#244]
**Describe the bug**
When the daemon is set to run on 1 minute intervals it can occur that a sync run for a large number of posts that were posted simultaneously takes longer than the 1 minute wait. This can produce a loop of the same post being sent multiple times.

**Comment by louisgrasset** [comment]
Hey, yes you are right. I'd say it's safer not to run this type of tool such often. The goal is to regular sync an account, not make it a live sync. I could add a `.lock` file to check between re-run or a minimum value between re-run, but I feel it should just not be used in this way
