### ISSUE TITLE
feat(docker): publish docker image to docker hub

### ISSUE THREAD

**Issue by joeblack2k** [louisgrasset/touitomamout#27]
is it possible to upload the docker to docker hub? so its more easily installed on things like Synology NAS and other more closed docker systems ?

**Comment by lleyton** [comment]
Alternatively, you could make the GHCR image [being built by CI](https://github.com/louisgrasset/touitomamout/blob/main/.github/workflows/docker.yml) public :p

**Comment by louisgrasset** [comment]
For now, I'll make the package public on GitHub here: https://github.com/users/louisgrasset/packages/container/package/touitomamout.

I'll soon start to work on properly publishing the image both on ghcr & docker hub 👍🏻

**Comment by louisgrasset** [comment]
Hey, I have some news:

🤖 A new workflow has been created ([here](https://github.com/louisgrasset/touitomamout/blob/main/.github/workflows/release.yml))

📦 Releases are now published on
1. [Github (GHCR)](https://github.com/louisgrasset/touitomamout/pkgs/container/touitomamout)
2. [Docker Hub](https://hub.docker.com/r/louisgrasset/touitomamout)

ℹ️ 3 types of image tags exist:
- `dev` : reflects the most recent changes on "main"
- `latest`: corresponds to the latest release

For now, the docker isn't restarting the sync on a defined schedule!
- `x.x.x`: specific versions
