### ISSUE TITLE
fix(bluesky): tweets longer than 300 chars fail to sync

### ISSUE THREAD

**Issue by mcleinn** [louisgrasset/touitomamout#28]
Thank you for your work! Synch to Mastodon works, but I actually need the script for Bluesky.

1. Yesterday I had an error like "Content too long, more than 300 symbols"
Probably X/Twitter Blue - which allows  long messages - is not supported? 
If Bluesky does not support long messages from Twitter Blue, then they should probably be split up? 
Or shortened with a link to the original X message? Or ignored? But not lead to an error.

Currently I cannot reproduce the error, probably because the new messages in the timeline are shorter
 
2. But there is now a second problem
`🦤 client: ✔ connected (session restored)
☁️ client: ✔ connected
profile-sync    √ task finished
content-mapper  √ tweets: total: 139 retweets: 0 replies: 0 quotes: 0
content-mapper  √ task finished
content-sync    - medias: ↓ (1/1) downloadingMedia type not supported (video/mp4)

🦤 → 🦣+☁️
Touitomamout sync
| Twitter handle: @myhandle
| 00000  ʲᵘˢᵗ ˢʸⁿᶜᵉᵈ ᵖᵒˢᵗˢ
| 00085  ˢʸⁿᶜᵉᵈ ᵖᵒˢᵗˢ ˢᵒ ᶠᵃʳ
content-sync    \ medias: ↑ (1/1) uploading`

And on this message it hangs up.

**Comment by louisgrasset** [comment]
Hello @mcleinn, thanks for this report! 

I did not tested the bot with longer tweets, my bad. That's something I will work on.
Splitting the content seems to be the best idea. This can have an impact on the way the bot caches the synced tweets.

I have to investigate on a clean implementation.

**Changes I have in mind:**
- Adapt the current cache system
  - Save each created post id for a (long) tweet. (currently it only saves the first (and only) post id
  - Take into account these multiple refenreces when you post a new tweet as response to the first one (so the bot generates your answers below the end of the last part)
  - Migrate the current stores structure so we don't mess everyone's data

**Comment by louisgrasset** [comment]
For the second issue, please open another Github Issue so we can properly follow each problem. It would be worth sharing your account or the related tweet that causes an issue. As far as I know, some specific type of media (such as some Gif responses) cannot be synced. It has been improved, but there is still some gap to fill
