### ISSUE TITLE
fix(bluesky): downloadingMedia type not supported (video/mp4)

### ISSUE THREAD

**Issue by mcleinn** [louisgrasset/touitomamout#29]
Thank you for considering my report about message lengths. Here is the separate report for the 2nd issue.

Script freezes when synching with Bluesky

```
🦤 client: ✔ connected (session restored)
☁️ client: ✔ connected
profile-sync √ task finished
content-mapper √ tweets: total: 139 retweets: 0 replies: 0 quotes: 0
content-mapper √ task finished
content-sync - medias: ↓ (1/1) downloadingMedia type not supported (video/mp4)
🦤 → 🦣+☁️
Touitomamout sync
| Twitter handle: @myhandle
| 00000 ʲᵘˢᵗ ˢʸⁿᶜᵉᵈ ᵖᵒˢᵗˢ
| 00085 ˢʸⁿᶜᵉᵈ ᵖᵒˢᵗˢ ˢᵒ ᶠᵃʳ
content-sync \ medias: ↑ (1/1) uploading
```
and then it freezes 

1. video/mp4 is a standard format, it should not cause issues
2. it is "uploading" something which it could not download, and it freezes
maybe something could be improved with error handling, not sure

the account I am trying to mirror to Bluesky is https://twitter.com/EuromaidanPress

**Comment by louisgrasset** [comment]
ℹ️  Currently, Bluesky does not support videos/gif (even from the web client itself)

**Refs:**

1. https://github.com/bluesky-social/atproto/discussions/1157
2. https://github.com/bluesky-social/atproto/issues/1603
3. https://github.com/bluesky-social/atproto/discussions/1604
4. https://github.com/bluesky-social/atproto/issues/1162

**Comment by louisgrasset** [comment]
Sure, that's why I did not close the issue. I'll work on this 🙉 .

Considering the way of thinking around Mastodon or Bluesky, my two cents would be not to post x links there. I'll prefer just skipping tweets with that kind of media.
